spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB
    username: C##kunal
    password: kunal123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none   # 🔥 change this
    show-sql: true
    

logging:
  level:
    root: INFO
    com.zorvyn.finance: DEBUG